"""followers

Revision ID: 615ed854d4cb
Revises: 4ddc0ba0fc55
Create Date: 2021-11-08 13:40:59.928847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615ed854d4cb'
down_revision = '4ddc0ba0fc55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
